In [93]:
import numpy as np

In [94]:
class ClosedLinReg():

    def __init__(self):
        self.coefs_ = None
        self.weights_ = None
        self.bias_ = 0.0
    
    def fit(self, X, y):
        X_full = np.c_[np.ones(X.shape[0]), X]
        self.coefs_ = np.linalg.inv(X_full.T @ X_full) @ X_full.T @ y
        self.weights_ = self.coefs_[1:]
        self.bias_ = self.coefs_[0]
    
    def predict(self, X, y):
        X_full = np.c_[np.ones(X.shape[0]), X]

        return X_full @ self.coefs_

        

In [95]:
from sklearn.datasets import fetch_california_housing
from sklearn.metrics import r2_score, mean_absolute_error

In [96]:
X, y = fetch_california_housing(return_X_y=True)
type(X)

numpy.ndarray

In [97]:
X.shape, y.shape

((20640, 8), (20640,))

In [98]:
y.dtype

dtype('float64')

In [99]:
model = ClosedLinReg()
model.fit(X, y)
model.weights_, model.bias_

(array([ 4.36693293e-01,  9.43577803e-03, -1.07322041e-01,  6.45065693e-01,
        -3.97638942e-06, -3.78654265e-03, -4.21314378e-01, -4.34513755e-01]),
 np.float64(-36.94192021321999))

In [100]:
y_preds = model.predict(X,y)
y_preds

array([4.13164983, 3.97660644, 3.67657094, ..., 0.17125141, 0.31910524,
       0.51580363], shape=(20640,))

In [105]:
y

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894], shape=(20640,))

In [106]:
r2_score(y, y_preds)

0.6062326851998052

In [107]:
mean_absolute_error(y, y_preds)

0.5311643817562935